title: Stackbit DIY Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    title: DIY
    logo: images/cloudhealy.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_links:
      - label: Inicio
        url: /
      - label: Features
        url: /features
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: About
        url: /about
        style: link
      - label: Blog
        url: /blog
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Contact
        url: /contact
        style: link
      - label: Get Started
        url: /pricing
        style: primary
    has_anncmnt: false
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    logo: images/classic/logo.svg
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - label: News
        url: /blog/category/news
        style: link
      - label: General
        url: /blog/category/general
        style: link
      - label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Instagram
        url: 'https://instagram.com/cloudhealy'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: Twitter
        url: 'https://twitter.com/cloudheaIy'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: GitHub
        url: 'https://github.com/cloudhealy'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: 'https://cr.linkedin.com/company/cloudhealy'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - label: Facebook
        url: 'https://facebook.com/cloudhealy'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
    content: >-
      &copy; 2021 Cloudhealy. All rights reserved.
  domain: 'https://site-template-30d56.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
